[package]
name = "gramr"
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

[lib]
name = "rust_gramr"
crate-type = ["staticlib"]

[dependencies]
log = "0.4.17"
cxx = "1.0"
im-rc = "15.0.0"
base64 = "0.13.0"
rustc-simple-version = "0.1.0"

[dependencies.soroban-env-host]
version = "0.0.15"
git = "https://github.com/stellar/rs-soroban-env"
rev = "aa7424dc2ea8db1391365e229f550d726734ae55"
features = ["vm"]

[dependencies.soroban-test-wasms]
git = "https://github.com/stellar/rs-soroban-env"
rev = "aa7424dc2ea8db1391365e229f550d726734ae55"
